# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: StockHawk CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1419A96209694BB0A02CF1EC5BA72751 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5536CE4B9F154C4F8A754D689F34E6BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBBBA561D974834A12A9727A4161A11 }}

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn add @types/node

      - name: Build with yarn
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: yarn install && yarn build
        working-directory: "${{ github.workspace }}/src/StockHawk.Web/"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: ./src/StockHawk.Web/dist

  deploy_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    needs: build_frontend
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-static-webapp.outputs.static_web_app_url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
      - name: Display structure of downloaded files
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1419A96209694BB0A02CF1EC5BA72751 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5536CE4B9F154C4F8A754D689F34E6BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBBBA561D974834A12A9727A4161A11 }}

      - name: Deploy to Azure Static Web App
        id: deploy-to-static-webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SMOKE_0A5139403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./" # App source code path
          ###### End of Repository/Build Configurations ######

  test_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test/StockHawk.UnitTests/
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: test with dotnet
        run: dotnet test

  build_backend:
    runs-on: ubuntu-latest
    needs: test_backend
    defaults:
      run:
        working-directory: ./src/StockHawk.API/
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1419A96209694BB0A02CF1EC5BA72751 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5536CE4B9F154C4F8A754D689F34E6BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBBBA561D974834A12A9727A4161A11 }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1419A96209694BB0A02CF1EC5BA72751 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5536CE4B9F154C4F8A754D689F34E6BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBBBA561D974834A12A9727A4161A11 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "StockHawk-api-deploy"
          slot-name: "Production"
          package: .

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SMOKE_0A5139403 }}
